_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
                - 55
            "4": 3.10.18
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 64
device:
    value: cuda
epochs:
    value: 1000000
initialize:
    value:
        output_proj:
            - uniform
            - 0.1
        qk:
            - uniform
            - 0.1
        v:
            - uniform
            - 0.1
learning_rate:
    value: 0.001
order:
    value: 1
sequence_length:
    value: 128
vocab_size:
    value: 5
